export const TMDB_API_KEY = "def35e965783fa51b992b6aec5d6b7ff";
export const TMDB_IMG = "https://image.tmdb.org/t/p/w500";
export const TMDB_BG  = "https://image.tmdb.org/t/p/original";

export const MOVIES = [

  // ── TRENDING NOW ──
  {
    id: 1, title: "Stranger Things",
    tmdbId: 66732, tmdbType: "tv",
    genre: "Sci-Fi · Horror", rating: "TV-14", match: 97, year: 2022, duration: "4 Seasons",
    description: "When a boy vanishes, a small town uncovers a mystery involving secret experiments and terrifying supernatural forces.",
    gradient: "linear-gradient(135deg,#0f0c29,#302b63,#24243e)",
    accentColor: "#e94560", heroGradient: "linear-gradient(to right,#0f0c29,#302b63,#0f0c29)",
    videoId: "b9EkMc79ZSU", category: "trending", tags: ["Dark","Suspenseful","Sci-Fi"], language: "English",
  },
  {
    id: 2, title: "Squid Game",
    tmdbId: 93405, tmdbType: "tv",
    genre: "Korean · Thriller", rating: "TV-MA", match: 98, year: 2021, duration: "2 Seasons",
    description: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games with deadly stakes.",
    gradient: "linear-gradient(135deg,#870000,#1f1c18,#870000)",
    accentColor: "#e74c3c", heroGradient: "linear-gradient(to right,#200122,#6f0000,#200122)",
    videoId: "oqxAJKy0ii4", category: "trending", tags: ["Intense","Award-Winning","Korean"], language: "Korean",
  },
  {
    id: 3, title: "Wednesday",
    tmdbId: 119051, tmdbType: "tv",
    genre: "Comedy · Horror", rating: "TV-14", match: 95, year: 2022, duration: "2 Seasons",
    description: "Wednesday Addams investigates a murder spree while making new friends and unleashing her psychic abilities at Nevermore Academy.",
    gradient: "linear-gradient(135deg,#1a1a1a,#2d2d2d,#434343)",
    accentColor: "#c0c0c0", heroGradient: "linear-gradient(to right,#050505,#1a1a1a,#050505)",
    videoId: "Di310WS63pk", category: "trending", tags: ["Dark Comedy","Mystery","Netflix"], language: "English",
  },
  {
    id: 4, title: "Arcane",
    tmdbId: 94605, tmdbType: "tv",
    genre: "Animation · Fantasy", rating: "TV-14", match: 99, year: 2021, duration: "2 Seasons",
    description: "Set in utopian Piltover and the oppressed underground of Zaun, two sisters fight on opposite sides of a brewing war.",
    gradient: "linear-gradient(135deg,#0d0d2b,#1a0533,#2d0a5c)",
    accentColor: "#9b59b6", heroGradient: "linear-gradient(to right,#050515,#0d0d2b,#050515)",
    videoId: "fXmAurh012s", category: "trending", tags: ["Animation","Emmy Award","League of Legends"], language: "English",
  },
  {
    id: 5, title: "Dark",
    tmdbId: 70523, tmdbType: "tv",
    genre: "German · Sci-Fi Thriller", rating: "TV-MA", match: 96, year: 2020, duration: "3 Seasons",
    description: "A missing child sets four families on a frantic hunt for answers as they unearth a mind-bending mystery spanning three generations.",
    gradient: "linear-gradient(135deg,#0f0c29,#302b63,#24243e)",
    accentColor: "#9b59b6", heroGradient: "linear-gradient(to right,#000000,#1a1a2e,#000000)",
    videoId: "rrwycJ08PSA", category: "trending", tags: ["Mind-bending","Time Travel","German"], language: "German",
  },

  // ── BLOCKBUSTER HITS ──
  {
    id: 11, title: "Oppenheimer",
    tmdbId: 872585, tmdbType: "movie",
    genre: "Drama · History", rating: "R", match: 98, year: 2023, duration: "3h",
    description: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    gradient: "linear-gradient(135deg,#1a0a00,#5c1a00,#8a2700)",
    accentColor: "#ff6b35", heroGradient: "linear-gradient(to right,#0a0500,#1a0a00,#0a0500)",
    videoId: "uYPbbksJxIg", category: "hits", tags: ["Oscar Winner","Christopher Nolan","History"], language: "English",
  },
  {
    id: 12, title: "Dune: Part Two",
    tmdbId: 693134, tmdbType: "movie",
    genre: "Sci-Fi · Epic", rating: "PG-13", match: 97, year: 2024, duration: "2h 46m",
    description: "Paul Atreides unites with the Fremen and begins a journey to seek revenge against the conspirators who destroyed his family.",
    gradient: "linear-gradient(135deg,#3d2b00,#7a5500,#c4900a)",
    accentColor: "#d4a017", heroGradient: "linear-gradient(to right,#150e00,#3d2b00,#150e00)",
    videoId: "Way9Dexny3w", category: "hits", tags: ["Epic","Sci-Fi","Denis Villeneuve"], language: "English",
  },
  {
    id: 13, title: "Interstellar",
    tmdbId: 157336, tmdbType: "movie",
    genre: "Sci-Fi · Drama", rating: "PG-13", match: 99, year: 2014, duration: "2h 49m",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    gradient: "linear-gradient(135deg,#0b0c2a,#1a237e,#283593)",
    accentColor: "#42a5f5", heroGradient: "linear-gradient(to right,#050510,#0b0c2a,#050510)",
    videoId: "zSWdZVtXT7E", category: "hits", tags: ["Space","Nolan","Mind-bending"], language: "English",
  },
  {
    id: 14, title: "Inception",
    tmdbId: 27205, tmdbType: "movie",
    genre: "Sci-Fi · Thriller", rating: "PG-13", match: 98, year: 2010, duration: "2h 28m",
    description: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea.",
    gradient: "linear-gradient(135deg,#1c1c1c,#2d2d2d,#0a3d62)",
    accentColor: "#3498db", heroGradient: "linear-gradient(to right,#050510,#0a1a35,#050510)",
    videoId: "YoHD9XEInc0", category: "hits", tags: ["Mind-bending","Thriller","Oscar Winner"], language: "English",
  },
  {
    id: 15, title: "The Batman",
    tmdbId: 414906, tmdbType: "movie",
    genre: "Action · Crime", rating: "PG-13", match: 95, year: 2022, duration: "2h 56m",
    description: "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a trail of cryptic clues.",
    gradient: "linear-gradient(135deg,#0a0a0a,#1c1c1c,#2d2d2d)",
    accentColor: "#c0c0c0", heroGradient: "linear-gradient(to right,#000000,#0a0a0a,#000000)",
    videoId: "mqqft2x_Aa4", category: "hits", tags: ["DC","Dark","Crime"], language: "English",
  },

  // ── NEW ON NETFLIX ──
  {
    id: 21, title: "ONE PIECE",
    tmdbId: 111110, tmdbType: "tv",
    genre: "Action · Adventure", rating: "TV-14", match: 97, year: 2023, duration: "2 Seasons",
    description: "With his straw hat and ragtag crew, young pirate Monkey D. Luffy goes on an epic voyage for the world's greatest treasure.",
    gradient: "linear-gradient(135deg,#0a2a6e,#1a5276,#2e86c1)",
    accentColor: "#f39c12", heroGradient: "linear-gradient(to right,#05102e,#0a2a6e,#05102e)",
    videoId: "uVzRRwHmDgQ", category: "new", tags: ["Anime","Adventure","Pirate"], language: "English",
  },
  {
    id: 22, title: "Zootopia 2",
    tmdbId: 1084242, tmdbType: "movie",
    genre: "Animation · Comedy", rating: "PG", match: 94, year: 2025, duration: "1h 49m",
    description: "Rookie cops Judy Hopps and Nick Wilde team up again when Gary De'Snake turns the animal metropolis upside down.",
    gradient: "linear-gradient(135deg,#e67e22,#f39c12,#f1c40f)",
    accentColor: "#f39c12", heroGradient: "linear-gradient(to right,#3d1e00,#7d3c00,#3d1e00)",
    videoId: "S_EdfMQIx-o", category: "new", tags: ["Disney","Family","Animation"], language: "English",
  },
  {
    id: 23, title: "Project Hail Mary",
    tmdbId: 687163, tmdbType: "movie",
    genre: "Sci-Fi · Drama", rating: "PG-13", match: 99, year: 2026, duration: "2h 15m",
    description: "Science teacher Ryland Grace wakes on a spaceship light-years from home with no memory, on a mission to save Earth.",
    gradient: "linear-gradient(135deg,#0b0c2a,#1a237e,#283593)",
    accentColor: "#42a5f5", heroGradient: "linear-gradient(to right,#050510,#0b0c2a,#050510)",
    videoId: "xnN5HkzpfMo", category: "new", tags: ["Space","Must-Watch","Ryan Gosling"], language: "English",
  },
  {
    id: 24, title: "KPop Demon Hunters",
    tmdbId: 803796, tmdbType: "movie",
    genre: "Animation · Action", rating: "PG", match: 95, year: 2025, duration: "1h 35m",
    description: "When K-pop superstars Rumi, Mira and Zoey aren't selling out stadiums, they're using secret powers to fight demons.",
    gradient: "linear-gradient(135deg,#880e4f,#ad1457,#e91e63)",
    accentColor: "#f48fb1", heroGradient: "linear-gradient(to right,#2a0020,#880e4f,#2a0020)",
    videoId: "kDiXxHm1A_4", category: "new", tags: ["K-Pop","Animation","Netflix"], language: "English",
  },
  {
    id: 25, title: "Good Luck, Have Fun, Don't Die",
    tmdbId: 1119449, tmdbType: "movie",
    genre: "Sci-Fi · Comedy", rating: "R", match: 91, year: 2026, duration: "2h 14m",
    description: "A man from the future recruits diner patrons on a one-night quest to save the world from a rogue AI.",
    gradient: "linear-gradient(135deg,#1a0533,#4a0e8f,#7b1fa2)",
    accentColor: "#ab47bc", heroGradient: "linear-gradient(to right,#0a0020,#1a0533,#0a0020)",
    videoId: "aaSa7b2u9Tg", category: "new", tags: ["Comedy","Sci-Fi","Action"], language: "English",
  },

  // ── POPULAR TV SHOWS ──
  {
    id: 31, title: "Breaking Bad",
    tmdbId: 1396, tmdbType: "tv",
    genre: "Crime · Drama", rating: "TV-MA", match: 99, year: 2013, duration: "5 Seasons",
    description: "A chemistry teacher dying of cancer teams with a former student to manufacture crystal meth to secure his family's future.",
    gradient: "linear-gradient(135deg,#134e5e,#71b280)",
    accentColor: "#71b280", heroGradient: "linear-gradient(to right,#0a1a0a,#134e5e,#0a1a0a)",
    videoId: "HhesaQXLuRY", category: "tvshows", tags: ["Crime","Acclaimed","Must Watch"], language: "English",
  },
  {
    id: 32, title: "Money Heist",
    tmdbId: 71446, tmdbType: "tv",
    genre: "Spanish · Crime", rating: "TV-MA", match: 96, year: 2021, duration: "5 Seasons",
    description: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history — stealing 2.4 billion euros.",
    gradient: "linear-gradient(135deg,#c0392b,#8e0000)",
    accentColor: "#e74c3c", heroGradient: "linear-gradient(to right,#3a0000,#8e0000,#3a0000)",
    videoId: "_InqQJRqGW4", category: "tvshows", tags: ["Heist","Spanish","Action"], language: "Spanish",
  },
  {
    id: 33, title: "Young Sheldon",
    tmdbId: 71728, tmdbType: "tv",
    genre: "Comedy · Family", rating: "TV-PG", match: 93, year: 2023, duration: "7 Seasons",
    description: "The childhood of Sheldon Cooper — a once-in-a-generation mind growing up in East Texas with his loving, bewildered family.",
    gradient: "linear-gradient(135deg,#1565c0,#1976d2,#42a5f5)",
    accentColor: "#42a5f5", heroGradient: "linear-gradient(to right,#051535,#1565c0,#051535)",
    videoId: "EBpzanYpwgs", category: "tvshows", tags: ["Comedy","Family","Big Bang Theory"], language: "English",
  },
  {
    id: 34, title: "Modern Family",
    tmdbId: 1421, tmdbType: "tv",
    genre: "Comedy · Family", rating: "TV-PG", match: 96, year: 2020, duration: "11 Seasons",
    description: "Three families face the trials of raising kids in a rapidly changing world in this beloved Emmy-winning mockumentary.",
    gradient: "linear-gradient(135deg,#795548,#a1887f,#d7ccc8)",
    accentColor: "#ff8f00", heroGradient: "linear-gradient(to right,#2d1e00,#5d3a00,#2d1e00)",
    videoId: "YqKP3X8bK3o", category: "tvshows", tags: ["Comedy","Emmy","Classic"], language: "English",
  },
  {
    id: 35, title: "Family Guy",
    tmdbId: 1434, tmdbType: "tv",
    genre: "Animation · Comedy", rating: "TV-14", match: 91, year: 2023, duration: "21 Seasons",
    description: "The Griffin family navigates life's absurdities with irreverent, boundary-pushing humor in Quahog, Rhode Island.",
    gradient: "linear-gradient(135deg,#1a237e,#283593,#3949ab)",
    accentColor: "#5c6bc0", heroGradient: "linear-gradient(to right,#080c35,#1a237e,#080c35)",
    videoId: "GfWUG-9-H7A", category: "tvshows", tags: ["Animation","Adult","Comedy"], language: "English",
  },
  {
    id: 36, title: "Bones",
    tmdbId: 1911, tmdbType: "tv",
    genre: "Crime · Drama", rating: "TV-14", match: 90, year: 2017, duration: "12 Seasons",
    description: "Forensic anthropologist Dr. Temperance Brennan and FBI agent Seeley Booth solve murders using skeletal remains.",
    gradient: "linear-gradient(135deg,#263238,#37474f,#546e7a)",
    accentColor: "#90a4ae", heroGradient: "linear-gradient(to right,#0a0d0f,#263238,#0a0d0f)",
    videoId: "yHJ5kDLSdSA", category: "tvshows", tags: ["Crime","Drama","Procedural"], language: "English",
  },

  // ── ACTION & FAMILY ──
  {
    id: 41, title: "The Avengers",
    tmdbId: 24428, tmdbType: "movie",
    genre: "Action · Superhero", rating: "PG-13", match: 98, year: 2012, duration: "2h 23m",
    description: "Earth's mightiest heroes must come together to stop Loki and his alien army from enslaving humanity.",
    gradient: "linear-gradient(135deg,#b71c1c,#0d47a1,#1b5e20)",
    accentColor: "#ef5350", heroGradient: "linear-gradient(to right,#1a0505,#0d1b2a,#1a0505)",
    videoId: "eOrNdBpGMv8", category: "family", tags: ["Marvel","Superhero","Action"], language: "English",
  },
  {
    id: 42, title: "Pirates of the Caribbean",
    tmdbId: 22, tmdbType: "movie",
    genre: "Action · Adventure", rating: "PG-13", match: 97, year: 2003, duration: "2h 23m",
    description: "Blacksmith Will Turner and eccentric Captain Jack Sparrow team up to rescue Elizabeth Swann from cursed pirates.",
    gradient: "linear-gradient(135deg,#1a0a00,#4e342e,#6d4c41)",
    accentColor: "#d4a017", heroGradient: "linear-gradient(to right,#0a0500,#1a0a00,#0a0500)",
    videoId: "naQr0uTrH_s", category: "family", tags: ["Disney","Adventure","Classic"], language: "English",
  },
  {
    id: 43, title: "PAW Patrol",
    tmdbId: 125392, tmdbType: "tv",
    genre: "Animation · Kids", rating: "TV-Y", match: 92, year: 2023, duration: "10 Seasons",
    description: "A boy named Ryder leads a pack of rescue dogs with unique skills, protecting Adventure Bay from all kinds of trouble.",
    gradient: "linear-gradient(135deg,#e53935,#fb8c00,#43a047)",
    accentColor: "#fb8c00", heroGradient: "linear-gradient(to right,#3a0800,#8b2500,#3a0800)",
    videoId: "5cqFpsFXUdg", category: "family", tags: ["Kids","Dogs","Animation"], language: "English",
  },
  {
    id: 44, title: "Troll 2",
    tmdbId: 1180831, tmdbType: "movie",
    genre: "Norwegian · Action", rating: "TV-14", match: 88, year: 2025, duration: "1h 40m",
    description: "Nora and Andreas face their most dangerous mission yet when a new devastating troll threatens their homeland.",
    gradient: "linear-gradient(135deg,#1b5e20,#2e7d32,#388e3c)",
    accentColor: "#66bb6a", heroGradient: "linear-gradient(to right,#091a09,#1b5e20,#091a09)",
    videoId: "2q16kx0FWrI", category: "family", tags: ["Norwegian","Creature","Netflix"], language: "Norwegian",
  },
  {
    id: 45, title: "Hoppers",
    tmdbId: 1327819, tmdbType: "movie",
    genre: "Animation · Sci-Fi", rating: "PG", match: 96, year: 2026, duration: "1h 45m",
    description: "Animal lover Mabel hops her consciousness into a robotic beaver to communicate with animals and save their habitat.",
    gradient: "linear-gradient(135deg,#1a5e20,#27ae60,#76d7c4)",
    accentColor: "#27ae60", heroGradient: "linear-gradient(to right,#0a2a10,#1a5e20,#0a2a10)",
    videoId: "qdU2OEFxNK8", category: "family", tags: ["Pixar","Family","Sci-Fi"], language: "English",
  },

  // ── WORLD CINEMA ──
  {
    id: 51, title: "Re/Member",
    tmdbId: 934440, tmdbType: "movie",
    genre: "Japanese · Horror", rating: "TV-MA", match: 87, year: 2022, duration: "1h 44m",
    description: "High school students are trapped in a death loop, forced to reassemble a body or relive the nightmare forever.",
    gradient: "linear-gradient(135deg,#4a0000,#870000,#c62828)",
    accentColor: "#ef5350", heroGradient: "linear-gradient(to right,#1a0000,#4a0000,#1a0000)",
    videoId: "yRPZ2CcDCPM", category: "world", tags: ["Horror","Japanese","Netflix"], language: "Japanese",
  },
  {
    id: 52, title: "Already Tomorrow in Hong Kong",
    tmdbId: 339148, tmdbType: "movie",
    genre: "Romance · Drama", rating: "NR", match: 85, year: 2015, duration: "1h 18m",
    description: "An American girl and an expat meet in Hong Kong, starting a romantic connection that unfolds over two nights.",
    gradient: "linear-gradient(135deg,#1a237e,#283593,#c62828)",
    accentColor: "#ef9a9a", heroGradient: "linear-gradient(to right,#080c35,#1a237e,#080c35)",
    videoId: "mBV3UOmfJuA", category: "world", tags: ["Romance","Hong Kong","Indie"], language: "English",
  },
  {
    id: 53, title: "Bāhubali: The Epic",
    tmdbId: 1511417, tmdbType: "movie",
    genre: "Telugu · Epic Fantasy", rating: "UA", match: 95, year: 2025, duration: "Series",
    description: "A mysterious child raised near a waterfall discovers the ancient kingdom of Mahishmati ruled by a cruel tyrant.",
    gradient: "linear-gradient(135deg,#7b3f00,#c8781a,#e6a817)",
    accentColor: "#f39c12", heroGradient: "linear-gradient(to right,#2a1500,#7b3f00,#2a1500)",
    videoId: "3xYYIFY73wc", category: "world", tags: ["Epic","Fantasy","Indian"], language: "Telugu",
  },
  {
    id: 54, title: "Turbulence",
    tmdbId: 1401778, tmdbType: "movie",
    genre: "Thriller · Action", rating: "R", match: 82, year: 2025, duration: "1h 40m",
    description: "A survivalist thriller where damaged passengers on a flight face deadly consequences from each other — and their secrets.",
    gradient: "linear-gradient(135deg,#263238,#455a64,#78909c)",
    accentColor: "#90a4ae", heroGradient: "linear-gradient(to right,#0a0d0f,#263238,#0a0d0f)",
    videoId: "QoXbHw3L1SY", category: "world", tags: ["Thriller","Action","Survival"], language: "English",
  },
  {
    id: 55, title: "Solo Mio",
    tmdbId: 1291335, tmdbType: "movie",
    genre: "Romance · Comedy", rating: "PG", match: 88, year: 2026, duration: "1h 36m",
    description: "Left heartbroken in Rome after a wedding disaster, a stranded groom finds transformation through a determined local.",
    gradient: "linear-gradient(135deg,#c0392b,#e74c3c,#e67e22)",
    accentColor: "#e74c3c", heroGradient: "linear-gradient(to right,#3a0000,#6e0000,#3a0000)",
    videoId: "tEgHhWMh2b8", category: "world", tags: ["Romance","Italy","Comedy"], language: "English",
  },

  // ── CARTOONS & ANIMATION ──
  {
    id: 61, title: "The Lion King",
    tmdbId: 8587, tmdbType: "movie",
    genre: "Animation · Adventure", rating: "G", match: 99, year: 1994, duration: "1h 28m",
    description: "A young lion prince flees his kingdom after the murder of his father, only to learn the true meaning of responsibility and bravery.",
    gradient: "linear-gradient(135deg,#7b3f00,#c8781a,#f5a623)",
    accentColor: "#f5a623", heroGradient: "linear-gradient(to right,#2a1500,#7b3f00,#2a1500)",
    videoId: "4sj1MT05lAA", category: "cartoon", tags: ["Disney","Classic","Musical"], language: "English",
  },
  {
    id: 62, title: "Spider-Man: Into the Spider-Verse",
    tmdbId: 324857, tmdbType: "movie",
    genre: "Animation · Superhero", rating: "PG", match: 99, year: 2018, duration: "1h 57m",
    description: "Teen Miles Morales becomes Spider-Man and must team up with Spider-People from alternate dimensions to save all realities.",
    gradient: "linear-gradient(135deg,#1a0533,#4a0e8f,#c0392b)",
    accentColor: "#e74c3c", heroGradient: "linear-gradient(to right,#0a0020,#1a0533,#0a0020)",
    videoId: "tg52up16eq0", category: "cartoon", tags: ["Marvel","Oscar Winner","Animation"], language: "English",
  },
  {
    id: 63, title: "Kung Fu Panda 4",
    tmdbId: 1011985, tmdbType: "movie",
    genre: "Animation · Comedy", rating: "PG", match: 93, year: 2024, duration: "1h 34m",
    description: "Po is chosen to become the Spiritual Leader of the Valley of Peace, but must first find and train a new Dragon Warrior.",
    gradient: "linear-gradient(135deg,#1b5e20,#33691e,#827717)",
    accentColor: "#aed581", heroGradient: "linear-gradient(to right,#091a09,#1b5e20,#091a09)",
    videoId: "w7vSMn_lOeI", category: "cartoon", tags: ["DreamWorks","Comedy","Action"], language: "English",
  },
  {
    id: 64, title: "Moana 2",
    tmdbId: 1241982, tmdbType: "movie",
    genre: "Animation · Musical", rating: "PG", match: 94, year: 2024, duration: "1h 40m",
    description: "Moana embarks on a far-reaching voyage to reach distant Motufetu and reunite separated peoples across the ocean.",
    gradient: "linear-gradient(135deg,#0277bd,#0288d1,#4fc3f7)",
    accentColor: "#4fc3f7", heroGradient: "linear-gradient(to right,#01304a,#0277bd,#01304a)",
    videoId: "1Z3kK9TzMdQ", category: "cartoon", tags: ["Disney","Musical","Adventure"], language: "English",
  },
  {
    id: 65, title: "Inside Out 2",
    tmdbId: 1022789, tmdbType: "movie",
    genre: "Animation · Drama", rating: "PG", match: 96, year: 2024, duration: "1h 40m",
    description: "Riley enters adolescence and new emotions Anxiety, Envy, Ennui and Embarrassment join her headquarters, causing chaos.",
    gradient: "linear-gradient(135deg,#e65100,#f57c00,#ffa726)",
    accentColor: "#ffa726", heroGradient: "linear-gradient(to right,#3e1700,#7b3300,#3e1700)",
    videoId: "LEjhY15eCx0", category: "cartoon", tags: ["Pixar","Emotional","Oscar Winner"], language: "English",
  },
  {
    id: 66, title: "Shrek",
    tmdbId: 808, tmdbType: "movie",
    genre: "Animation · Comedy", rating: "PG", match: 98, year: 2001, duration: "1h 30m",
    description: "A mean but lovable ogre goes on a quest to rescue a princess with a donkey he can't seem to get rid of.",
    gradient: "linear-gradient(135deg,#33691e,#558b2f,#7cb342)",
    accentColor: "#8bc34a", heroGradient: "linear-gradient(to right,#0d1f09,#33691e,#0d1f09)",
    videoId: "CwziTLDGSeA", category: "cartoon", tags: ["DreamWorks","Classic","Comedy"], language: "English",
  },
  {
    id: 67, title: "How to Train Your Dragon",
    tmdbId: 10191, tmdbType: "movie",
    genre: "Animation · Adventure", rating: "PG", match: 98, year: 2010, duration: "1h 38m",
    description: "A young Viking forms an unlikely friendship with a dragon, challenging his entire village's beliefs about their ancient enemies.",
    gradient: "linear-gradient(135deg,#0d47a1,#1565c0,#283593)",
    accentColor: "#42a5f5", heroGradient: "linear-gradient(to right,#050c35,#0d47a1,#050c35)",
    videoId: "oKiYuIsPxYk", category: "cartoon", tags: ["DreamWorks","Dragon","Fantasy"], language: "English",
  },
  {
    id: 68, title: "Elemental",
    tmdbId: 976573, tmdbType: "movie",
    genre: "Animation · Adventure", rating: "PG", match: 91, year: 2023, duration: "1h 41m",
    description: "Ember and Wade discover an elemental city where fire, water, land, and air residents live together — and learn they're not so different.",
    gradient: "linear-gradient(135deg,#bf360c,#e64a19,#ff7043)",
    accentColor: "#ff7043", heroGradient: "linear-gradient(to right,#3e0d00,#8b2500,#3e0d00)",
    videoId: "hXzcyx9V0xw", category: "cartoon", tags: ["Pixar","Heartfelt","Colorful"], language: "English",
  },
  {
    id: 69, title: "Puss in Boots: The Last Wish",
    tmdbId: 315162, tmdbType: "movie",
    genre: "Animation · Adventure", rating: "PG", match: 98, year: 2022, duration: "1h 42m",
    description: "Puss discovers he has burned through eight of his nine lives and embarks on a journey to find the mythical Last Wish.",
    gradient: "linear-gradient(135deg,#6a1a00,#bf360c,#e64a19)",
    accentColor: "#ff8a65", heroGradient: "linear-gradient(to right,#220800,#6a1a00,#220800)",
    videoId: "F2tN8t_-D7E", category: "cartoon", tags: ["DreamWorks","Exciting","Critically Acclaimed"], language: "English",
  },
  {
    id: 70, title: "The Super Mario Bros. Movie",
    tmdbId: 569094, tmdbType: "movie",
    genre: "Animation · Adventure", rating: "PG", match: 92, year: 2023, duration: "1h 32m",
    description: "Mario and Luigi are transported to a magical kingdom where Mario must grow into a hero to save his brother and stop Bowser.",
    gradient: "linear-gradient(135deg,#b71c1c,#c62828,#e53935)",
    accentColor: "#ff5252", heroGradient: "linear-gradient(to right,#3e0808,#b71c1c,#3e0808)",
    videoId: "TnGl01FkMMo", category: "cartoon", tags: ["Nintendo","Family","Action"], language: "English",
  },
  {
    id: 71, title: "Minions: The Rise of Gru",
    tmdbId: 438148, tmdbType: "movie",
    genre: "Animation · Comedy", rating: "PG", match: 89, year: 2022, duration: "1h 27m",
    description: "Young Gru and his Minions discover the supervillain group Vicious 6 — and set out to join them by stealing a powerful stone.",
    gradient: "linear-gradient(135deg,#f9a825,#f57f17,#e65100)",
    accentColor: "#ffd54f", heroGradient: "linear-gradient(to right,#3e2800,#7a5000,#3e2800)",
    videoId: "mNBSFdMxiBc", category: "cartoon", tags: ["Illumination","Comedy","Kids"], language: "English",
  },
  {
    id: 72, title: "Turning Red",
    tmdbId: 508947, tmdbType: "movie",
    genre: "Animation · Comedy", rating: "PG", match: 93, year: 2022, duration: "1h 40m",
    description: "13-year-old Meilin discovers she turns into a giant red panda whenever she gets too excited in this Pixar coming-of-age tale.",
    gradient: "linear-gradient(135deg,#880e4f,#ad1457,#e91e63)",
    accentColor: "#f48fb1", heroGradient: "linear-gradient(to right,#2a0020,#880e4f,#2a0020)",
    videoId: "XdKzUbAiZDI", category: "cartoon", tags: ["Pixar","Coming-of-Age","Funny"], language: "English",
  },

  // ── EPIC ADVENTURES ──
  {
    id: 81, title: "Avatar: The Way of Water",
    tmdbId: 76600, tmdbType: "movie",
    genre: "Sci-Fi · Adventure", rating: "PG-13", match: 95, year: 2022, duration: "3h 12m",
    description: "Jake Sully and Neytiri fight to keep their family together and battle the forces that threaten their ocean home on Pandora.",
    gradient: "linear-gradient(135deg,#006064,#00838f,#4dd0e1)",
    accentColor: "#4dd0e1", heroGradient: "linear-gradient(to right,#001a1b,#006064,#001a1b)",
    videoId: "a8Gx8wiNbs8", category: "adventure", tags: ["Epic","Visuals","Cameron"], language: "English",
  },
  {
    id: 82, title: "Indiana Jones and the Dial of Destiny",
    tmdbId: 335977, tmdbType: "movie",
    genre: "Action · Adventure", rating: "PG-13", match: 88, year: 2023, duration: "2h 34m",
    description: "Archaeologist and adventurer Indiana Jones races against time to retrieve a legendary dial that can change the course of history.",
    gradient: "linear-gradient(135deg,#5d4037,#795548,#a1887f)",
    accentColor: "#d4a017", heroGradient: "linear-gradient(to right,#1a1000,#5d4037,#1a1000)",
    videoId: "eQfMbSe7F2g", category: "adventure", tags: ["Harrison Ford","Action","Classic"], language: "English",
  },
  {
    id: 83, title: "Doctor Strange in the Multiverse of Madness",
    tmdbId: 453395, tmdbType: "movie",
    genre: "Superhero · Horror", rating: "PG-13", match: 91, year: 2022, duration: "2h 6m",
    description: "Doctor Strange must navigate the dangerous Multiverse to protect America Chavez from a powerful, terrifying adversary.",
    gradient: "linear-gradient(135deg,#4a0e8f,#6a1b9a,#7b1fa2)",
    accentColor: "#ce93d8", heroGradient: "linear-gradient(to right,#1a0533,#4a0e8f,#1a0533)",
    videoId: "aWzlQ2N6qqg", category: "adventure", tags: ["Marvel","Multiverse","Horror"], language: "English",
  },
  {
    id: 84, title: "Thor: Love and Thunder",
    tmdbId: 616037, tmdbType: "movie",
    genre: "Superhero · Comedy", rating: "PG-13", match: 87, year: 2022, duration: "1h 59m",
    description: "Thor embarks on a journey unlike anything he has ever faced — a quest for inner peace — but is interrupted by a galactic killer.",
    gradient: "linear-gradient(135deg,#0d47a1,#1565c0,#ffd600)",
    accentColor: "#ffd600", heroGradient: "linear-gradient(to right,#030e35,#0d47a1,#030e35)",
    videoId: "tgB1wUcmbbw", category: "adventure", tags: ["Marvel","Taika Waititi","Comedy"], language: "English",
  },
  {
    id: 85, title: "Guardians of the Galaxy Vol. 3",
    tmdbId: 447365, tmdbType: "movie",
    genre: "Superhero · Comedy", rating: "PG-13", match: 95, year: 2023, duration: "2h 30m",
    description: "The Guardians set out on a mission to protect one of their own — a mission that threatens to unravel them if not successful.",
    gradient: "linear-gradient(135deg,#880e4f,#1565c0,#1b5e20)",
    accentColor: "#ce93d8", heroGradient: "linear-gradient(to right,#200820,#1a0533,#200820)",
    videoId: "u3V5KDHRQvk", category: "adventure", tags: ["Marvel","Emotional","Action"], language: "English",
  },
  {
    id: 86, title: "Jurassic World Dominion",
    tmdbId: 507086, tmdbType: "movie",
    genre: "Sci-Fi · Adventure", rating: "PG-13", match: 84, year: 2022, duration: "2h 27m",
    description: "Four years after the destruction of Isla Nublar, dinosaurs now live and hunt alongside humans — and the world is at the brink.",
    gradient: "linear-gradient(135deg,#1b5e20,#2e7d32,#4caf50)",
    accentColor: "#a5d6a7", heroGradient: "linear-gradient(to right,#091a09,#1b5e20,#091a09)",
    videoId: "fb5ELWi-ekk", category: "adventure", tags: ["Dinosaurs","Action","Epic"], language: "English",
  },
  {
    id: 87, title: "Black Panther: Wakanda Forever",
    tmdbId: 505642, tmdbType: "movie",
    genre: "Superhero · Drama", rating: "PG-13", match: 93, year: 2022, duration: "2h 41m",
    description: "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T'Challa.",
    gradient: "linear-gradient(135deg,#1a237e,#283593,#880e4f)",
    accentColor: "#ce93d8", heroGradient: "linear-gradient(to right,#080c35,#1a237e,#080c35)",
    videoId: "RlOB3UALvrQ", category: "adventure", tags: ["Marvel","Emotional","Wakanda"], language: "English",
  },
  {
    id: 88, title: "Top Gun: Maverick",
    tmdbId: 361743, tmdbType: "movie",
    genre: "Action · Adventure", rating: "PG-13", match: 97, year: 2022, duration: "2h 11m",
    description: "After thirty years, Maverick is still pushing the envelope as a top naval aviator, while confronting the ghosts of his past.",
    gradient: "linear-gradient(135deg,#0d47a1,#1565c0,#e65100)",
    accentColor: "#ff8a65", heroGradient: "linear-gradient(to right,#030e35,#0d47a1,#030e35)",
    videoId: "giXco2jaZ_4", category: "adventure", tags: ["Tom Cruise","Action","Thrilling"], language: "English",
  },
  {
    id: 89, title: "Mission: Impossible – Dead Reckoning",
    tmdbId: 575264, tmdbType: "movie",
    genre: "Action · Thriller", rating: "PG-13", match: 96, year: 2023, duration: "2h 43m",
    description: "Ethan Hunt and his IMF team must track down a terrifying new weapon — a sentient AI — before it falls into the wrong hands.",
    gradient: "linear-gradient(135deg,#263238,#37474f,#b71c1c)",
    accentColor: "#ef5350", heroGradient: "linear-gradient(to right,#0a0d0f,#263238,#0a0d0f)",
    videoId: "avz06PDqgIM", category: "adventure", tags: ["Tom Cruise","Stunts","Thriller"], language: "English",
  },
  {
    id: 90, title: "Wonka",
    tmdbId: 901362, tmdbType: "movie",
    genre: "Fantasy · Musical", rating: "PG", match: 92, year: 2023, duration: "1h 56m",
    description: "The story of how the young Willy Wonka came to be the world's greatest inventor, magician, and chocolate maker.",
    gradient: "linear-gradient(135deg,#880e4f,#c2185b,#f06292)",
    accentColor: "#f48fb1", heroGradient: "linear-gradient(to right,#2a0020,#880e4f,#2a0020)",
    videoId: "otNh9bTjXWg", category: "adventure", tags: ["Fantasy","Musical","Timothée Chalamet"], language: "English",
  },

  // ── EXTRA TRENDING (to reach 20) ──
  { id: 101, title: "The Witcher", tmdbId: 71912, tmdbType: "tv", genre: "Fantasy · Action", rating: "TV-MA", match: 94, year: 2021, duration: "3 Seasons", description: "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world.", gradient: "linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)", accentColor: "#e94560", heroGradient: "linear-gradient(to right,#050510,#1a1a2e,#050510)", videoId: "ndl1W4ltcmg", category: "trending", tags: ["Fantasy","Henry Cavill","Action"], language: "English" },
  { id: 102, title: "Ozark", tmdbId: 69740, tmdbType: "tv", genre: "Crime · Drama", rating: "TV-MA", match: 96, year: 2022, duration: "4 Seasons", description: "A financial advisor drags his family from Chicago to the Missouri Ozarks, where he must launder money to appease a drug boss.", gradient: "linear-gradient(135deg,#0d1b2a,#1b2838,#2a3a4a)", accentColor: "#4fc3f7", heroGradient: "linear-gradient(to right,#050a0f,#0d1b2a,#050a0f)", videoId: "5hAXVqrljbs", category: "trending", tags: ["Crime","Thriller","Drama"], language: "English" },
  { id: 103, title: "Euphoria", tmdbId: 85552, tmdbType: "tv", genre: "Teen Drama", rating: "TV-MA", match: 93, year: 2022, duration: "2 Seasons", description: "A group of high school students navigate love and friendships in a world of drugs, sex, trauma, and social media.", gradient: "linear-gradient(135deg,#1a003a,#2d0060,#4a0099)", accentColor: "#bb86fc", heroGradient: "linear-gradient(to right,#0a0020,#1a003a,#0a0020)", videoId: "Yl7s3fUOlKw", category: "trending", tags: ["Drama","Teen","Intense"], language: "English" },
  { id: 104, title: "House of the Dragon", tmdbId: 94997, tmdbType: "tv", genre: "Fantasy · Drama", rating: "TV-MA", match: 97, year: 2022, duration: "2 Seasons", description: "The story of House Targaryen set 200 years before the events of Game of Thrones.", gradient: "linear-gradient(135deg,#1a0a00,#3d1c00,#7a3800)", accentColor: "#ff6d00", heroGradient: "linear-gradient(to right,#0a0500,#1a0a00,#0a0500)", videoId: "DotnJ7tTA34", category: "trending", tags: ["Fantasy","HBO","Dragons"], language: "English" },
  { id: 105, title: "The Last of Us", tmdbId: 100088, tmdbType: "tv", genre: "Post-Apocalyptic", rating: "TV-MA", match: 99, year: 2023, duration: "2 Seasons", description: "Joel must smuggle Ellie, a teenage girl who is the key to a cure, across a post-apocalyptic America.", gradient: "linear-gradient(135deg,#1b2a0a,#2d4a10,#3d6b18)", accentColor: "#8bc34a", heroGradient: "linear-gradient(to right,#0a1005,#1b2a0a,#0a1005)", videoId: "uLtkt8BonwM", category: "trending", tags: ["HBO","Survival","Emotional"], language: "English" },
  { id: 106, title: "Peaky Blinders", tmdbId: 46648, tmdbType: "tv", genre: "Crime · Drama", rating: "TV-MA", match: 98, year: 2022, duration: "6 Seasons", description: "A gangster family epic set in 1919 Birmingham, England, centering on a gang who sew razor blades in the peaks of their caps.", gradient: "linear-gradient(135deg,#0a0a0a,#1c1c1c,#2d2d2d)", accentColor: "#bbb", heroGradient: "linear-gradient(to right,#000,#0a0a0a,#000)", videoId: "oVzVdvGIC7U", category: "trending", tags: ["Crime","British","Period Drama"], language: "English" },
  { id: 107, title: "Severance", tmdbId: 123249, tmdbType: "tv", genre: "Sci-Fi · Thriller", rating: "TV-MA", match: 97, year: 2023, duration: "2 Seasons", description: "Mark leads a team whose memories have been surgically divided between their work and personal lives.", gradient: "linear-gradient(135deg,#0a1a2a,#1a2a3a,#2a3a50)", accentColor: "#60a5fa", heroGradient: "linear-gradient(to right,#030810,#0a1a2a,#030810)", videoId: "xEQP4VVuyrY", category: "trending", tags: ["Apple TV+","Mystery","Mindbending"], language: "English" },
  { id: 108, title: "Black Mirror", tmdbId: 42009, tmdbType: "tv", genre: "Sci-Fi · Anthology", rating: "TV-MA", match: 95, year: 2023, duration: "6 Seasons", description: "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.", gradient: "linear-gradient(135deg,#0a0a0a,#1a1a1a,#111)", accentColor: "#eee", heroGradient: "linear-gradient(to right,#000,#0a0a0a,#000)", videoId: "jDiYGjDmoRo", category: "trending", tags: ["Technology","Dark","Anthology"], language: "English" },
  { id: 109, title: "Better Call Saul", tmdbId: 60059, tmdbType: "tv", genre: "Crime · Drama", rating: "TV-MA", match: 99, year: 2022, duration: "6 Seasons", description: "The story of Jimmy McGill's transformation into criminal lawyer Saul Goodman before his partnership with Walter White.", gradient: "linear-gradient(135deg,#2a1a00,#5c3a00,#8a5a00)", accentColor: "#ffd700", heroGradient: "linear-gradient(to right,#100800,#2a1a00,#100800)", videoId: "HN4oydykJFc", category: "trending", tags: ["Crime","Prequel","Drama"], language: "English" },
  { id: 110, title: "The Crown", tmdbId: 65494, tmdbType: "tv", genre: "Historical Drama", rating: "TV-MA", match: 94, year: 2023, duration: "6 Seasons", description: "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the 20th century.", gradient: "linear-gradient(135deg,#1a0a2e,#2d1a4a,#4a2a70)", accentColor: "#c9a96e", heroGradient: "linear-gradient(to right,#0a0515,#1a0a2e,#0a0515)", videoId: "JWtnJjn6ng0", category: "trending", tags: ["Royal","British","Period"], language: "English" },
  { id: 111, title: "Ted Lasso", tmdbId: 97546, tmdbType: "tv", genre: "Comedy · Sports", rating: "TV-MA", match: 97, year: 2023, duration: "3 Seasons", description: "An American college football coach is hired to manage an English football club, despite no experience in the sport.", gradient: "linear-gradient(135deg,#003087,#034694,#2563eb)", accentColor: "#60a5fa", heroGradient: "linear-gradient(to right,#001040,#003087,#001040)", videoId: "3u7EIiohs6U", category: "trending", tags: ["Apple TV+","Heartwarming","Comedy"], language: "English" },
  { id: 112, title: "Andor", tmdbId: 83867, tmdbType: "tv", genre: "Sci-Fi · Action", rating: "TV-14", match: 96, year: 2022, duration: "2 Seasons", description: "The story of the burgeoning rebellion against the Empire — a prequel to Rogue One: A Star Wars Story.", gradient: "linear-gradient(135deg,#0d1b2a,#1a3a5c,#2a5a8a)", accentColor: "#60a5fa", heroGradient: "linear-gradient(to right,#050a10,#0d1b2a,#050a10)", videoId: "cKOegEuCcfw", category: "trending", tags: ["Star Wars","Disney+","Gritty"], language: "English" },
  { id: 113, title: "The Bear", tmdbId: 136315, tmdbType: "tv", genre: "Drama · Comedy", rating: "TV-MA", match: 98, year: 2023, duration: "3 Seasons", description: "A young chef from the fine dining world returns to Chicago to run his family's sandwich shop.", gradient: "linear-gradient(135deg,#1a1000,#3a2800,#5a4000)", accentColor: "#f59e0b", heroGradient: "linear-gradient(to right,#0a0800,#1a1000,#0a0800)", videoId: "MxUQZMFW2Go", category: "trending", tags: ["FX","Intense","Food"], language: "English" },
  { id: 114, title: "Succession", tmdbId: 62560, tmdbType: "tv", genre: "Drama · Satire", rating: "TV-MA", match: 99, year: 2023, duration: "4 Seasons", description: "The Roy family controls one of the biggest media and entertainment conglomerates in the world. It's not always easy.", gradient: "linear-gradient(135deg,#1a1a1a,#2d2d2d,#3d2000)", accentColor: "#d4a017", heroGradient: "linear-gradient(to right,#0a0a0a,#1a1a1a,#0a0a0a)", videoId: "OzYxJV_rmE8", category: "trending", tags: ["HBO","Power","Satire"], language: "English" },
  { id: 115, title: "Shogun", tmdbId: 37854, tmdbType: "tv", genre: "Historical · Action", rating: "TV-MA", match: 98, year: 2024, duration: "1 Season", description: "A powerful Japanese warlord's fate intertwines with a shipwrecked English navigator in feudal Japan.", gradient: "linear-gradient(135deg,#1a0000,#3a0000,#5a0000)", accentColor: "#ef4444", heroGradient: "linear-gradient(to right,#0a0000,#1a0000,#0a0000)", videoId: "oNIJlZ-mNfs", category: "trending", tags: ["FX","Japan","Epic"], language: "Japanese" },

  // ── EXTRA HITS (to reach 20) ──
  { id: 121, title: "The Dark Knight", tmdbId: 155, tmdbType: "movie", genre: "Action · Crime", rating: "PG-13", match: 99, year: 2008, duration: "2h 32m", description: "Batman raises the stakes in his war on crime. With the help of allies, he battles the Joker — a criminal genius who will reduce Gotham to chaos.", gradient: "linear-gradient(135deg,#0a0a0a,#1c1c1c,#0a0a3a)", accentColor: "#3a86ff", heroGradient: "linear-gradient(to right,#000,#0a0a0a,#000)", videoId: "EXeTwQWrcwY", category: "hits", tags: ["Christopher Nolan","Joker","Classic"], language: "English" },
  { id: 122, title: "Everything Everywhere All at Once", tmdbId: 545611, tmdbType: "movie", genre: "Sci-Fi · Comedy", rating: "R", match: 98, year: 2022, duration: "2h 19m", description: "A middle-aged Chinese immigrant is swept up in an adventure to save the multiverse and reconnect with her daughter.", gradient: "linear-gradient(135deg,#1a0030,#0030a0,#00a060)", accentColor: "#00ff88", heroGradient: "linear-gradient(to right,#0a0018,#1a0030,#0a0018)", videoId: "wxN1T1uxQ2g", category: "hits", tags: ["A24","Oscar Winner","Multiverse"], language: "English" },
  { id: 123, title: "Parasite", tmdbId: 496243, tmdbType: "movie", genre: "Korean · Thriller", rating: "R", match: 99, year: 2019, duration: "2h 12m", description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", gradient: "linear-gradient(135deg,#0a0a0a,#1a1a1a,#2a2a2a)", accentColor: "#f59e0b", heroGradient: "linear-gradient(to right,#000,#0a0a0a,#000)", videoId: "5xH0HfJHsaY", category: "hits", tags: ["Palme d'Or","Korean","Oscar Winner"], language: "Korean" },
  { id: 124, title: "The Godfather", tmdbId: 238, tmdbType: "movie", genre: "Crime · Drama", rating: "R", match: 100, year: 1972, duration: "2h 55m", description: "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.", gradient: "linear-gradient(135deg,#1a0a00,#3a1a00,#5a2a00)", accentColor: "#c9a96e", heroGradient: "linear-gradient(to right,#0a0500,#1a0a00,#0a0500)", videoId: "sY1S34973zA", category: "hits", tags: ["Classic","Crime","Masterpiece"], language: "English" },
  { id: 125, title: "Whiplash", tmdbId: 244786, tmdbType: "movie", genre: "Drama · Music", rating: "R", match: 98, year: 2014, duration: "1h 47m", description: "A young drummer pursues greatness at a music conservatory under an abusive instructor.", gradient: "linear-gradient(135deg,#1a0a00,#3a1a00,#1a1a1a)", accentColor: "#e5a100", heroGradient: "linear-gradient(to right,#0a0500,#1a0a00,#0a0500)", videoId: "7d_jQycdQGo", category: "hits", tags: ["Music","Intense","Oscar Winner"], language: "English" },
  { id: 126, title: "La La Land", tmdbId: 313369, tmdbType: "movie", genre: "Romance · Musical", rating: "PG-13", match: 95, year: 2016, duration: "2h 8m", description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.", gradient: "linear-gradient(135deg,#1a0040,#2d006a,#5c0aa0)", accentColor: "#f9a8d4", heroGradient: "linear-gradient(to right,#0a0020,#1a0040,#0a0020)", videoId: "0pdqf4P9MB8", category: "hits", tags: ["Musical","Romance","Oscar Winner"], language: "English" },
  { id: 127, title: "Get Out", tmdbId: 419430, tmdbType: "movie", genre: "Horror · Thriller", rating: "R", match: 96, year: 2017, duration: "1h 44m", description: "A young African-American visits his white girlfriend's parents for the weekend, where his uneasiness grows with each encounter.", gradient: "linear-gradient(135deg,#0a1a0a,#1a3a1a,#2a5a2a)", accentColor: "#4ade80", heroGradient: "linear-gradient(to right,#050a05,#0a1a0a,#050a05)", videoId: "DzfpyUB60YY", category: "hits", tags: ["Jordan Peele","Horror","Social Thriller"], language: "English" },
  { id: 128, title: "Mad Max: Fury Road", tmdbId: 76341, tmdbType: "movie", genre: "Action · Sci-Fi", rating: "R", match: 97, year: 2015, duration: "2h", description: "In a post-apocalyptic wasteland, Max teams with rebel warrior Furiosa to overthrow a cult tyrant controlling water and oil.", gradient: "linear-gradient(135deg,#3d1a00,#7a3a00,#c46200)", accentColor: "#f97316", heroGradient: "linear-gradient(to right,#1a0800,#3d1a00,#1a0800)", videoId: "hEJnMQG9ev8", category: "hits", tags: ["Action","Post-Apocalyptic","Oscar Winner"], language: "English" },
  { id: 129, title: "Tár", tmdbId: 792307, tmdbType: "movie", genre: "Drama · Music", rating: "R", match: 94, year: 2022, duration: "2h 38m", description: "A complex portrait of Lydia Tár, considered one of the greatest living composers and conductors.", gradient: "linear-gradient(135deg,#1a1a2e,#16213e,#0f3460)", accentColor: "#93c5fd", heroGradient: "linear-gradient(to right,#080810,#1a1a2e,#080810)", videoId: "oRLaF4Nm9Ic", category: "hits", tags: ["Cate Blanchett","Drama","Music"], language: "English" },
  { id: 130, title: "Arrival", tmdbId: 329865, tmdbType: "movie", genre: "Sci-Fi · Drama", rating: "PG-13", match: 97, year: 2016, duration: "1h 56m", description: "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecrafts appear around the world.", gradient: "linear-gradient(135deg,#0d1b2a,#1e3a5f,#2a5a8a)", accentColor: "#7dd3fc", heroGradient: "linear-gradient(to right,#050a10,#0d1b2a,#050a10)", videoId: "IsXDAdKlemY", category: "hits", tags: ["Denis Villeneuve","Sci-Fi","Emotional"], language: "English" },
  { id: 131, title: "Hereditary", tmdbId: 493922, tmdbType: "movie", genre: "Horror · Drama", rating: "R", match: 93, year: 2018, duration: "2h 7m", description: "When the matriarch of the Graham family passes away, her daughter's family begins to unravel dark secrets.", gradient: "linear-gradient(135deg,#1a0a00,#2a1000,#0a0a1a)", accentColor: "#c084fc", heroGradient: "linear-gradient(to right,#0a0500,#1a0a00,#0a0500)", videoId: "V6wWKNij7Rk", category: "hits", tags: ["A24","Horror","Ari Aster"], language: "English" },
  { id: 132, title: "1917", tmdbId: 530915, tmdbType: "movie", genre: "War · Drama", rating: "R", match: 97, year: 2019, duration: "1h 59m", description: "Two British soldiers are sent on a seemingly impossible mission behind enemy lines to deliver a message that could save 1,600 men.", gradient: "linear-gradient(135deg,#1a1a00,#2d2d00,#3d3d10)", accentColor: "#d4a017", heroGradient: "linear-gradient(to right,#0a0a00,#1a1a00,#0a0a00)", videoId: "YqNYrYUiMfg", category: "hits", tags: ["Sam Mendes","War","One Shot"], language: "English" },
  { id: 133, title: "The Revenant", tmdbId: 281957, tmdbType: "movie", genre: "Adventure · Drama", rating: "R", match: 95, year: 2015, duration: "2h 36m", description: "A frontiersman on a fur trading expedition fights for survival after being mauled by a bear.", gradient: "linear-gradient(135deg,#0a1a2a,#1a2a3a,#0a0a0a)", accentColor: "#93c5fd", heroGradient: "linear-gradient(to right,#030810,#0a1a2a,#030810)", videoId: "LoebZZ8K5N0", category: "hits", tags: ["DiCaprio","Oscar Winner","Survival"], language: "English" },
  { id: 134, title: "Knives Out", tmdbId: 546554, tmdbType: "movie", genre: "Mystery · Comedy", rating: "PG-13", match: 96, year: 2019, duration: "2h 10m", description: "A detective investigates the death of a patriarch of an eccentric, combative family.", gradient: "linear-gradient(135deg,#1a1a00,#2a2a10,#3a3a1a)", accentColor: "#fbbf24", heroGradient: "linear-gradient(to right,#0a0a00,#1a1a00,#0a0a00)", videoId: "xi-1NchUqMA", category: "hits", tags: ["Mystery","Daniel Craig","Rian Johnson"], language: "English" },
  { id: 135, title: "The Menu", tmdbId: 593643, tmdbType: "movie", genre: "Thriller · Horror", rating: "R", match: 92, year: 2022, duration: "1h 47m", description: "A young couple travels to a remote island to eat at an exclusive restaurant, where the chef has prepared a menu with some shocking surprises.", gradient: "linear-gradient(135deg,#0a1a0a,#1a3a1a,#0a0a0a)", accentColor: "#86efac", heroGradient: "linear-gradient(to right,#050a05,#0a1a0a,#050a05)", videoId: "vFEFg_DPVCo", category: "hits", tags: ["Food","Dark Comedy","Thriller"], language: "English" },

  // ── EXTRA NEW ON NETFLIX (to reach 20) ──
  { id: 141, title: "Ripley", tmdbId: 106215, tmdbType: "tv", genre: "Crime · Drama", rating: "TV-MA", match: 95, year: 2024, duration: "1 Season", description: "A con man schemes and murders his way through 1960s Italy, trying to escape his past and assume a new identity.", gradient: "linear-gradient(135deg,#0a0a0a,#1a1a2a,#2a2a3a)", accentColor: "#e2e8f0", heroGradient: "linear-gradient(to right,#000,#0a0a0a,#000)", videoId: "6MHTcHMIHek", category: "new", tags: ["Netflix","Black & White","Crime"], language: "English" },
  { id: 142, title: "Baby Reindeer", tmdbId: 245418, tmdbType: "tv", genre: "Drama · Thriller", rating: "TV-MA", match: 96, year: 2024, duration: "1 Season", description: "A struggling comedian's life is upended when he is stalked by an obsessive woman.", gradient: "linear-gradient(135deg,#0a1a2a,#1a2a3a,#2a3a4a)", accentColor: "#93c5fd", heroGradient: "linear-gradient(to right,#030810,#0a1a2a,#030810)", videoId: "HeJBXdI7MB8", category: "new", tags: ["Netflix","Thriller","True Story"], language: "English" },
  { id: 143, title: "Fallout", tmdbId: 207538, tmdbType: "tv", genre: "Sci-Fi · Action", rating: "TV-MA", match: 97, year: 2024, duration: "1 Season", description: "The haves and the have-nots in post-nuclear America — based on the popular video game franchise.", gradient: "linear-gradient(135deg,#1a1000,#3a2800,#c8a000)", accentColor: "#fbbf24", heroGradient: "linear-gradient(to right,#0a0800,#1a1000,#0a0800)", videoId: "xy8AiCLf_dk", category: "new", tags: ["Amazon","Video Game","Post-Apocalyptic"], language: "English" },
  { id: 144, title: "3 Body Problem", tmdbId: 108545, tmdbType: "tv", genre: "Sci-Fi · Drama", rating: "TV-MA", match: 94, year: 2024, duration: "1 Season", description: "A fateful decision made in 1960s China reverberates across space and time to a group of scientists in the present day.", gradient: "linear-gradient(135deg,#0d1b2a,#1a3060,#2a4a9a)", accentColor: "#818cf8", heroGradient: "linear-gradient(to right,#050810,#0d1b2a,#050810)", videoId: "k2GaHRDFR8o", category: "new", tags: ["Netflix","Hard Sci-Fi","Epic"], language: "English" },
  { id: 145, title: "Shōgun", tmdbId: 37854, tmdbType: "tv", genre: "Historical · Epic", rating: "TV-MA", match: 98, year: 2024, duration: "1 Season", description: "An English navigator is shipwrecked in feudal Japan and must navigate its complex political landscape.", gradient: "linear-gradient(135deg,#1a0000,#3a1000,#5c1000)", accentColor: "#ef4444", heroGradient: "linear-gradient(to right,#0a0000,#1a0000,#0a0000)", videoId: "oNIJlZ-mNfs", category: "new", tags: ["FX","Emmy Award","Japan"], language: "Japanese" },
  { id: 146, title: "Presumed Innocent", tmdbId: 247752, tmdbType: "tv", genre: "Legal · Thriller", rating: "TV-MA", match: 91, year: 2024, duration: "1 Season", description: "A prosecutor is charged with the murder of a colleague with whom he was having an affair.", gradient: "linear-gradient(135deg,#1a1a1a,#2a2a2a,#3a2a0a)", accentColor: "#fbbf24", heroGradient: "linear-gradient(to right,#0a0a0a,#1a1a1a,#0a0a0a)", videoId: "W_yGE4Zn_sU", category: "new", tags: ["Apple TV+","Legal","Thriller"], language: "English" },
  { id: 147, title: "Slow Horses", tmdbId: 103768, tmdbType: "tv", genre: "Spy · Thriller", rating: "TV-MA", match: 95, year: 2024, duration: "4 Seasons", description: "A dysfunctional team of British intelligence agents serve as a dumping ground for spies who've failed in various ways.", gradient: "linear-gradient(135deg,#0a1a0a,#1a2a1a,#1a1a0a)", accentColor: "#86efac", heroGradient: "linear-gradient(to right,#050a05,#0a1a0a,#050a05)", videoId: "m70lFuKDhlI", category: "new", tags: ["Apple TV+","Spy","Gary Oldman"], language: "English" },
  { id: 148, title: "The Acolyte", tmdbId: 114472, tmdbType: "tv", genre: "Sci-Fi · Action", rating: "TV-14", match: 82, year: 2024, duration: "1 Season", description: "An investigation into a shocking crime spree pits a respected Jedi Master against a dangerous warrior from his past.", gradient: "linear-gradient(135deg,#0a0a1a,#1a1a3a,#2a2a5a)", accentColor: "#a78bfa", heroGradient: "linear-gradient(to right,#050508,#0a0a1a,#050508)", videoId: "2ZDkW2Wt1Rk", category: "new", tags: ["Star Wars","Disney+","Action"], language: "English" },
  { id: 149, title: "A Man on the Inside", tmdbId: 237459, tmdbType: "tv", genre: "Comedy · Drama", rating: "TV-14", match: 93, year: 2024, duration: "1 Season", description: "A recently widowed professor goes undercover as a new resident in a retirement home to solve a mystery.", gradient: "linear-gradient(135deg,#0a2a1a,#1a4a2a,#2a6a3a)", accentColor: "#4ade80", heroGradient: "linear-gradient(to right,#050f0a,#0a2a1a,#050f0a)", videoId: "3Rk-l5wd6Mc", category: "new", tags: ["Netflix","Comedy","Ted Danson"], language: "English" },
  { id: 150, title: "Black Doves", tmdbId: 258813, tmdbType: "tv", genre: "Spy · Action", rating: "TV-MA", match: 89, year: 2024, duration: "1 Season", description: "A government spy living undercover as a politician's wife goes on the run after her secret lover is murdered.", gradient: "linear-gradient(135deg,#0a0a1a,#1a1a3a,#0a0a0a)", accentColor: "#818cf8", heroGradient: "linear-gradient(to right,#050508,#0a0a1a,#050508)", videoId: "YnmOnI2t_iM", category: "new", tags: ["Netflix","Spy","Keira Knightley"], language: "English" },
  { id: 151, title: "The Diplomat", tmdbId: 202250, tmdbType: "tv", genre: "Political · Drama", rating: "TV-MA", match: 94, year: 2024, duration: "2 Seasons", description: "A career diplomat unexpectedly lands the role of US Ambassador to the UK amidst an international crisis.", gradient: "linear-gradient(135deg,#0a1a2a,#1a2a3a,#1a1a2a)", accentColor: "#60a5fa", heroGradient: "linear-gradient(to right,#030810,#0a1a2a,#030810)", videoId: "1gLxCW6KOa8", category: "new", tags: ["Netflix","Politics","Drama"], language: "English" },
  { id: 152, title: "The Gentleman", tmdbId: 208759, tmdbType: "tv", genre: "Crime · Action", rating: "TV-MA", match: 92, year: 2024, duration: "1 Season", description: "An aristocratic young British man discovers his family's estate has long been sitting atop a cannabis empire.", gradient: "linear-gradient(135deg,#0a1a0a,#1a3a1a,#2a5a2a)", accentColor: "#4ade80", heroGradient: "linear-gradient(to right,#050a05,#0a1a0a,#050a05)", videoId: "vxm5EuDJ8nM", category: "new", tags: ["Netflix","Guy Ritchie","Crime"], language: "English" },
  { id: 153, title: "Adolescence", tmdbId: 258920, tmdbType: "tv", genre: "Drama · Crime", rating: "TV-MA", match: 99, year: 2025, duration: "1 Season", description: "A 13-year-old boy is arrested for the murder of a classmate, leaving his family and community in shock.", gradient: "linear-gradient(135deg,#0a0a0a,#1a1a1a,#0a1a0a)", accentColor: "#86efac", heroGradient: "linear-gradient(to right,#050505,#0a0a0a,#050505)", videoId: "R0CDpB3QCLE", category: "new", tags: ["Netflix","One-Shot","Crime"], language: "English" },
  { id: 154, title: "XO Kitty", tmdbId: 206484, tmdbType: "tv", genre: "Romance · Comedy", rating: "TV-14", match: 88, year: 2024, duration: "2 Seasons", description: "Love expert Kitty Song Covey moves to Korea to be with her long-distance boyfriend, but things don't go as planned.", gradient: "linear-gradient(135deg,#2d0040,#5a0080,#8000c0)", accentColor: "#f0abfc", heroGradient: "linear-gradient(to right,#150020,#2d0040,#150020)", videoId: "1WMFoakzrz8", category: "new", tags: ["Netflix","K-Drama","Romance"], language: "English" },
  { id: 155, title: "Running Point", tmdbId: 279873, tmdbType: "tv", genre: "Comedy · Sports", rating: "TV-MA", match: 90, year: 2025, duration: "1 Season", description: "The only daughter of a pro basketball team's ownership family must prove herself after her father names her team president.", gradient: "linear-gradient(135deg,#0a1a3a,#1a3a5a,#2a5a8a)", accentColor: "#60a5fa", heroGradient: "linear-gradient(to right,#050a15,#0a1a3a,#050a15)", videoId: "S2gFoC6i_xY", category: "new", tags: ["Netflix","Basketball","Comedy"], language: "English" },

  // ── EXTRA CARTOONS (to reach 20) ──
  { id: 161, title: "Bluey", tmdbId: 78261, tmdbType: "tv", genre: "Kids · Animation", rating: "TV-G", match: 99, year: 2023, duration: "7 Seasons", description: "Bluey is an irrepressible six-year-old Blue Heeler puppy who loves to play and turn everyday family moments into extraordinary adventures.", gradient: "linear-gradient(135deg,#0044aa,#0066cc,#0088ee)", accentColor: "#7dd3fc", heroGradient: "linear-gradient(to right,#002255,#0044aa,#002255)", videoId: "hJG4pqEGo7M", category: "cartoon", tags: ["Kids","Australian","Wholesome"], language: "English" },
  { id: 162, title: "Rick and Morty", tmdbId: 60625, tmdbType: "tv", genre: "Animation · Sci-Fi", rating: "TV-MA", match: 97, year: 2023, duration: "7 Seasons", description: "An eccentric, genius scientist drags his good-natured grandson on insane adventures across the universe.", gradient: "linear-gradient(135deg,#003a00,#007a00,#00cc44)", accentColor: "#4ade80", heroGradient: "linear-gradient(to right,#001a00,#003a00,#001a00)", videoId: "KgKLOoW4GPM", category: "cartoon", tags: ["Adult Animation","Sci-Fi","Comedy"], language: "English" },
  { id: 163, title: "Gravity Falls", tmdbId: 40075, tmdbType: "tv", genre: "Mystery · Animation", rating: "TV-G", match: 98, year: 2016, duration: "2 Seasons", description: "Twin siblings Dipper and Mabel Pines spend the summer in the mysterious Gravity Falls, Oregon, unraveling supernatural secrets.", gradient: "linear-gradient(135deg,#0a1a2a,#1a3a5a,#0a2a3a)", accentColor: "#60a5fa", heroGradient: "linear-gradient(to right,#050810,#0a1a2a,#050810)", videoId: "PZMBuBIzQbA", category: "cartoon", tags: ["Mystery","Kids","Disney"], language: "English" },
  { id: 164, title: "Avatar: The Last Airbender", tmdbId: 246, tmdbType: "tv", genre: "Animation · Fantasy", rating: "TV-Y7", match: 99, year: 2008, duration: "3 Seasons", description: "In a war-torn world of elemental magic, a young boy reawakens to undertake a perilous journey to fulfill his destiny as the Avatar.", gradient: "linear-gradient(135deg,#0044aa,#006644,#aa6600)", accentColor: "#fbbf24", heroGradient: "linear-gradient(to right,#002255,#0044aa,#002255)", videoId: "d1EnW4J4oEg", category: "cartoon", tags: ["Classic","Fantasy","Epic"], language: "English" },
  { id: 165, title: "BoJack Horseman", tmdbId: 61222, tmdbType: "tv", genre: "Animation · Drama", rating: "TV-MA", match: 97, year: 2019, duration: "6 Seasons", description: "Meet BoJack Horseman — the star of the '90s sitcom 'Horsin' Around', trying to find his way in a modern world.", gradient: "linear-gradient(135deg,#1a3a6a,#2a5a9a,#3a7aba)", accentColor: "#60a5fa", heroGradient: "linear-gradient(to right,#0a1a35,#1a3a6a,#0a1a35)", videoId: "eXPfqGPlcRo", category: "cartoon", tags: ["Netflix","Adult","Dark Comedy"], language: "English" },
  { id: 166, title: "Castlevania", tmdbId: 69990, tmdbType: "tv", genre: "Animation · Action", rating: "TV-MA", match: 95, year: 2021, duration: "4 Seasons", description: "A vampire hunter fights to save a besieged city from an army of otherworldly creatures controlled by Dracula.", gradient: "linear-gradient(135deg,#1a0030,#3a0060,#5a0090)", accentColor: "#c084fc", heroGradient: "linear-gradient(to right,#0a0018,#1a0030,#0a0018)", videoId: "iDeXb1JE_bE", category: "cartoon", tags: ["Netflix","Dark","Action"], language: "English" },
  { id: 167, title: "Demon Slayer", tmdbId: 85937, tmdbType: "tv", genre: "Anime · Action", rating: "TV-14", match: 98, year: 2023, duration: "4 Seasons", description: "A young boy becomes a demon slayer after his family is slaughtered and his younger sister is turned into a demon.", gradient: "linear-gradient(135deg,#1a0020,#2a0040,#440000)", accentColor: "#f87171", heroGradient: "linear-gradient(to right,#0a0010,#1a0020,#0a0010)", videoId: "FGvSxk_QeaY", category: "cartoon", tags: ["Anime","Action","Emotional"], language: "Japanese" },
  { id: 168, title: "Attack on Titan", tmdbId: 1429, tmdbType: "tv", genre: "Anime · Dark Fantasy", rating: "TV-MA", match: 99, year: 2023, duration: "4 Seasons", description: "In a world where humanity lives inside enormous walled cities, giant humanoid creatures called Titans terrorize the population.", gradient: "linear-gradient(135deg,#1a0a00,#3a1a00,#5a2a00)", accentColor: "#f97316", heroGradient: "linear-gradient(to right,#0a0500,#1a0a00,#0a0500)", videoId: "MGRm4IzK1SQ", category: "cartoon", tags: ["Anime","Dark","Epic"], language: "Japanese" },

  // ── EXTRA FAMILY / ACTION (to reach 20) ──
  { id: 171, title: "Sonic the Hedgehog 2", tmdbId: 675353, tmdbType: "movie", genre: "Family · Action", rating: "PG", match: 91, year: 2022, duration: "2h 2m", description: "Sonic the Hedgehog is back and faster than ever in the next chapter with Tails and Knuckles joining the fray.", gradient: "linear-gradient(135deg,#003087,#0066cc,#0099ff)", accentColor: "#60a5fa", heroGradient: "linear-gradient(to right,#001540,#003087,#001540)", videoId: "Oq-jMDKCnUo", category: "family", tags: ["Family","Action","Video Game"], language: "English" },
  { id: 172, title: "Jumanji: Welcome to the Jungle", tmdbId: 353486, tmdbType: "movie", genre: "Adventure · Comedy", rating: "PG-13", match: 93, year: 2017, duration: "1h 59m", description: "Four teenagers are sucked into a magical video game and the only way they can escape is to work together to finish the game.", gradient: "linear-gradient(135deg,#1a3a0a,#2a5a1a,#3a7a2a)", accentColor: "#86efac", heroGradient: "linear-gradient(to right,#0a1505,#1a3a0a,#0a1505)", videoId: "cWBEbPsYMmY", category: "family", tags: ["Action","Comedy","Dwayne Johnson"], language: "English" },
  { id: 173, title: "The Jungle Book", tmdbId: 278927, tmdbType: "movie", genre: "Family · Adventure", rating: "PG", match: 94, year: 2016, duration: "1h 46m", description: "After a threat from the tiger Shere Khan, Mowgli goes on a journey of self-discovery in the jungles of India.", gradient: "linear-gradient(135deg,#0a3a00,#1a6a00,#2a9a00)", accentColor: "#86efac", heroGradient: "linear-gradient(to right,#051500,#0a3a00,#051500)", videoId: "5mkm22yO-bs", category: "family", tags: ["Disney","Live Action","Family"], language: "English" },
  { id: 174, title: "Thor", tmdbId: 10195, tmdbType: "movie", genre: "Superhero · Action", rating: "PG-13", match: 90, year: 2011, duration: "1h 55m", description: "The powerful but arrogant god Thor is cast out of Asgard to live amongst humans in Midgard as a punishment.", gradient: "linear-gradient(135deg,#0d47a1,#1565c0,#ffd600)", accentColor: "#ffd600", heroGradient: "linear-gradient(to right,#030e35,#0d47a1,#030e35)", videoId: "JOddp-nlNvQ", category: "family", tags: ["Marvel","Action","Chris Hemsworth"], language: "English" },
  { id: 175, title: "Captain America", tmdbId: 1771, tmdbType: "movie", genre: "Superhero · Action", rating: "PG-13", match: 92, year: 2011, duration: "2h 4m", description: "Steve Rogers, a rejected military soldier, transforms into Captain America after taking a dose of a Super-Soldier serum.", gradient: "linear-gradient(135deg,#003087,#990000,#ffffff44)", accentColor: "#60a5fa", heroGradient: "linear-gradient(to right,#001540,#003087,#001540)", videoId: "JerVrbLldXw", category: "family", tags: ["Marvel","Action","WWII"], language: "English" },
  { id: 176, title: "Spider-Man: No Way Home", tmdbId: 634649, tmdbType: "movie", genre: "Superhero · Action", rating: "PG-13", match: 98, year: 2021, duration: "2h 28m", description: "Peter Parker's life is upended when his identity as Spider-Man is revealed. He asks Doctor Strange for help, with far-reaching consequences.", gradient: "linear-gradient(135deg,#1a003a,#003a8a,#8a0000)", accentColor: "#f87171", heroGradient: "linear-gradient(to right,#0a0020,#001540,#0a0020)", videoId: "JfVOs4VSpmA", category: "family", tags: ["Marvel","Multiverse","Emotional"], language: "English" },
  { id: 177, title: "Black Widow", tmdbId: 497698, tmdbType: "movie", genre: "Superhero · Action", rating: "PG-13", match: 88, year: 2021, duration: "2h 14m", description: "Natasha Romanoff confronts the darker parts of her ledger when a dangerous conspiracy arises from her past.", gradient: "linear-gradient(135deg,#1a0000,#2a1a1a,#1a1a2a)", accentColor: "#f87171", heroGradient: "linear-gradient(to right,#0a0000,#1a0000,#0a0000)", videoId: "Fp9pNPdNwjI", category: "family", tags: ["Marvel","Action","Spy"], language: "English" },
  { id: 178, title: "Ant-Man and the Wasp", tmdbId: 363088, tmdbType: "movie", genre: "Superhero · Comedy", rating: "PG-13", match: 89, year: 2018, duration: "1h 58m", description: "Scott Lang and Hope van Dyne team up and go on an urgent new mission to rescue Hope's mother from the quantum realm.", gradient: "linear-gradient(135deg,#0a2a0a,#1a5a1a,#c00000)", accentColor: "#f87171", heroGradient: "linear-gradient(to right,#050f05,#0a2a0a,#050f05)", videoId: "e5Xh7jSHpAk", category: "family", tags: ["Marvel","Comedy","Action"], language: "English" },
  { id: 179, title: "Kung Fu Panda 3", tmdbId: 140300, tmdbType: "movie", genre: "Animation · Comedy", rating: "PG", match: 91, year: 2016, duration: "1h 35m", description: "Continuing his adventure with the Furious Five, Po must become a teacher when old villain Kai seeks to eliminate all kung fu masters.", gradient: "linear-gradient(135deg,#1a0a00,#3a1a00,#5a2a00)", accentColor: "#fbbf24", heroGradient: "linear-gradient(to right,#0a0500,#1a0a00,#0a0500)", videoId: "13QOdZe9Ee0", category: "family", tags: ["DreamWorks","Family","Comedy"], language: "English" },
  { id: 180, title: "The Incredibles", tmdbId: 9806, tmdbType: "movie", genre: "Animation · Action", rating: "PG", match: 99, year: 2004, duration: "1h 55m", description: "A family of undercover superheroes, while trying to live the quiet suburban life, are forced into action to save the world.", gradient: "linear-gradient(135deg,#8a0000,#cc2200,#ff6600)", accentColor: "#fb923c", heroGradient: "linear-gradient(to right,#400000,#8a0000,#400000)", videoId: "eZbzbC9285I", category: "family", tags: ["Pixar","Classic","Action"], language: "English" },
  { id: 181, title: "Brave", tmdbId: 62177, tmdbType: "movie", genre: "Animation · Adventure", rating: "PG", match: 93, year: 2012, duration: "1h 33m", description: "Determined to make her own path in life, Princess Merida defies a custom that brings chaos to her kingdom.", gradient: "linear-gradient(135deg,#0a2a00,#1a5a00,#2a8a00)", accentColor: "#86efac", heroGradient: "linear-gradient(to right,#051000,#0a2a00,#051000)", videoId: "TEHWDA_NFNM", category: "family", tags: ["Pixar","Princess","Adventure"], language: "English" },
  { id: 182, title: "Coco", tmdbId: 354912, tmdbType: "movie", genre: "Animation · Family", rating: "PG", match: 97, year: 2017, duration: "1h 45m", description: "Aspiring musician Miguel is magically transported to the vibrant Land of the Dead, where he seeks out his great-great-grandfather.", gradient: "linear-gradient(135deg,#3a0060,#6a00aa,#9a1a00)", accentColor: "#f97316", heroGradient: "linear-gradient(to right,#1a0030,#3a0060,#1a0030)", videoId: "Ga6RYejo6Hk", category: "family", tags: ["Pixar","Mexico","Music"], language: "English" },
  { id: 183, title: "Encanto", tmdbId: 568124, tmdbType: "movie", genre: "Animation · Musical", rating: "PG", match: 95, year: 2021, duration: "1h 39m", description: "The Madrigals are a magical family living in the mountains of Colombia. Every child has been blessed with a unique gift — except Mirabel.", gradient: "linear-gradient(135deg,#1a4000,#2a7000,#3a9a00)", accentColor: "#86efac", heroGradient: "linear-gradient(to right,#0a1f00,#1a4000,#0a1f00)", videoId: "CaimKeDcudo", category: "family", tags: ["Disney","Colombia","Musical"], language: "English" },
  { id: 184, title: "Raya and the Last Dragon", tmdbId: 527774, tmdbType: "movie", genre: "Animation · Adventure", rating: "PG", match: 92, year: 2021, duration: "1h 47m", description: "In a world called Kumandra, a human and a dragon must reunite to stop ancient evil spirits known as the Druun.", gradient: "linear-gradient(135deg,#1a0030,#3a0060,#5a1a00)", accentColor: "#f97316", heroGradient: "linear-gradient(to right,#0a0018,#1a0030,#0a0018)", videoId: "1VIZ89FEjYI", category: "family", tags: ["Disney","Adventure","Southeast Asia"], language: "English" },
  { id: 185, title: "Lightyear", tmdbId: 78209, tmdbType: "movie", genre: "Animation · Sci-Fi", rating: "PG", match: 87, year: 2022, duration: "1h 40m", description: "The origin story of Buzz Lightyear, the legendary space ranger, that inspired the beloved toy.", gradient: "linear-gradient(135deg,#0a1a3a,#1a3a6a,#2a5a9a)", accentColor: "#60a5fa", heroGradient: "linear-gradient(to right,#050810,#0a1a3a,#050810)", videoId: "BwZs9UFmqgA", category: "family", tags: ["Pixar","Toy Story","Space"], language: "English" },

  // ── EXTRA TV SHOWS (to reach 20) ──
  { id: 191, title: "Game of Thrones", tmdbId: 1399, tmdbType: "tv", genre: "Fantasy · Drama", rating: "TV-MA", match: 97, year: 2019, duration: "8 Seasons", description: "Nine noble families wage war against each other in order to gain control of the mythical land of Westeros.", gradient: "linear-gradient(135deg,#1a1a2e,#16213e,#0a0a1a)", accentColor: "#fbbf24", heroGradient: "linear-gradient(to right,#0a0a15,#1a1a2e,#0a0a15)", videoId: "KPLWWIOCOOQ", category: "tvshows", tags: ["HBO","Fantasy","Epic"], language: "English" },
  { id: 192, title: "Friends", tmdbId: 1668, tmdbType: "tv", genre: "Comedy · Sitcom", rating: "TV-14", match: 98, year: 2004, duration: "10 Seasons", description: "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.", gradient: "linear-gradient(135deg,#8a4000,#cc6600,#ffaa00)", accentColor: "#fbbf24", heroGradient: "linear-gradient(to right,#401800,#8a4000,#401800)", videoId: "VoBqMGr8ZdA", category: "tvshows", tags: ["Classic","Comedy","Sitcom"], language: "English" },
  { id: 193, title: "The Mandalorian", tmdbId: 82856, tmdbType: "tv", genre: "Sci-Fi · Western", rating: "TV-14", match: 96, year: 2023, duration: "3 Seasons", description: "A lone bounty hunter makes his way through the outer reaches of the galaxy, far from the authority of the New Republic.", gradient: "linear-gradient(135deg,#1a1000,#3a2800,#5a4000)", accentColor: "#d4a017", heroGradient: "linear-gradient(to right,#0a0800,#1a1000,#0a0800)", videoId: "aOC8E8z_ifw", category: "tvshows", tags: ["Star Wars","Disney+","Baby Yoda"], language: "English" },
  { id: 194, title: "Bridgerton", tmdbId: 106223, tmdbType: "tv", genre: "Romance · Period Drama", rating: "TV-MA", match: 92, year: 2023, duration: "3 Seasons", description: "The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society.", gradient: "linear-gradient(135deg,#2a0040,#4a0070,#6a00a0)", accentColor: "#f0abfc", heroGradient: "linear-gradient(to right,#150020,#2a0040,#150020)", videoId: "gpv7ayf_tyE", category: "tvshows", tags: ["Netflix","Romance","Period"], language: "English" },
  { id: 195, title: "Yellowstone", tmdbId: 73586, tmdbType: "tv", genre: "Western · Drama", rating: "TV-MA", match: 94, year: 2023, duration: "5 Seasons", description: "A ranching family in Montana fights against land developers, an Indian reservation, and America's first national park.", gradient: "linear-gradient(135deg,#1a0a00,#2a1a00,#3a2a00)", accentColor: "#d4a017", heroGradient: "linear-gradient(to right,#0a0500,#1a0a00,#0a0500)", videoId: "UKe6UZT5mBo", category: "tvshows", tags: ["Kevin Costner","Western","Drama"], language: "English" },
  { id: 196, title: "Abbott Elementary", tmdbId: 145403, tmdbType: "tv", genre: "Comedy · Mockumentary", rating: "TV-14", match: 96, year: 2024, duration: "4 Seasons", description: "A group of dedicated teachers — and one less-than-dedicated principal — navigate the trials of working in an underfunded school.", gradient: "linear-gradient(135deg,#1a2a0a,#2a4a1a,#3a6a2a)", accentColor: "#86efac", heroGradient: "linear-gradient(to right,#0a1505,#1a2a0a,#0a1505)", videoId: "gG-VwKBGwN8", category: "tvshows", tags: ["ABC","Comedy","Emmy Winner"], language: "English" },
  { id: 197, title: "Stranger Things", tmdbId: 66732, tmdbType: "tv", genre: "Sci-Fi · Horror", rating: "TV-14", match: 97, year: 2022, duration: "4 Seasons", description: "When a boy vanishes, a small town uncovers a mystery involving secret experiments and terrifying supernatural forces.", gradient: "linear-gradient(135deg,#0f0c29,#302b63,#24243e)", accentColor: "#e94560", heroGradient: "linear-gradient(to right,#0f0c29,#302b63,#0f0c29)", videoId: "b9EkMc79ZSU", category: "tvshows", tags: ["Netflix","80s","Supernatural"], language: "English" },
  { id: 198, title: "The Office (US)", tmdbId: 2316, tmdbType: "tv", genre: "Comedy · Mockumentary", rating: "TV-14", match: 99, year: 2013, duration: "9 Seasons", description: "A mockumentary on a group of typical office workers, where the workday consists of ego clashes, pranks, and love affairs.", gradient: "linear-gradient(135deg,#1a1a3a,#2a2a5a,#3a3a7a)", accentColor: "#93c5fd", heroGradient: "linear-gradient(to right,#0a0a1a,#1a1a3a,#0a0a1a)", videoId: "LHOtME2DL4g", category: "tvshows", tags: ["Comedy","Classic","Steve Carell"], language: "English" },
  { id: 199, title: "Suits", tmdbId: 37680, tmdbType: "tv", genre: "Legal · Drama", rating: "TV-14", match: 93, year: 2019, duration: "9 Seasons", description: "A brilliant college dropout begins working for a top Manhattan legal closer, while keeping his secret from others.", gradient: "linear-gradient(135deg,#0a1a2a,#1a2a3a,#0a0a1a)", accentColor: "#93c5fd", heroGradient: "linear-gradient(to right,#030810,#0a1a2a,#030810)", videoId: "bkC9SX-2oQ4", category: "tvshows", tags: ["Legal","Drama","Netflix"], language: "English" },
  { id: 200, title: "The Walking Dead", tmdbId: 1402, tmdbType: "tv", genre: "Horror · Drama", rating: "TV-MA", match: 91, year: 2022, duration: "11 Seasons", description: "Sheriff Deputy Rick Grimes wakes up from a coma to find a post-apocalyptic world dominated by flesh-eating zombies.", gradient: "linear-gradient(135deg,#1a0a00,#2a1a00,#1a1a0a)", accentColor: "#86efac", heroGradient: "linear-gradient(to right,#0a0500,#1a0a00,#0a0500)", videoId: "TNVcP-gkzzU", category: "tvshows", tags: ["AMC","Zombies","Survival"], language: "English" },
  { id: 201, title: "House of Cards", tmdbId: 1396, tmdbType: "tv", genre: "Political · Thriller", rating: "TV-MA", match: 90, year: 2018, duration: "6 Seasons", description: "A ruthless and cunning politician and his wife scheme to exact revenge on those who betray them.", gradient: "linear-gradient(135deg,#0a0a1a,#1a1a2a,#2a2a3a)", accentColor: "#93c5fd", heroGradient: "linear-gradient(to right,#050508,#0a0a1a,#050508)", videoId: "8QiPFmIMxFc", category: "tvshows", tags: ["Netflix","Politics","Kevin Spacey"], language: "English" },
  { id: 202, title: "Stranger Things S5", tmdbId: 66733, tmdbType: "tv", genre: "Sci-Fi · Horror", rating: "TV-14", match: 99, year: 2025, duration: "1 Season", description: "The final season of the Duffer Brothers' beloved sci-fi horror series. Hawkins faces its ultimate battle.", gradient: "linear-gradient(135deg,#0f0c29,#302b63,#24243e)", accentColor: "#e94560", heroGradient: "linear-gradient(to right,#0f0c29,#302b63,#0f0c29)", videoId: "b9EkMc79ZSU", category: "tvshows", tags: ["Netflix","Final Season","Sci-Fi"], language: "English" },
  { id: 203, title: "Lost", tmdbId: 4607, tmdbType: "tv", genre: "Mystery · Sci-Fi", rating: "TV-14", match: 94, year: 2010, duration: "6 Seasons", description: "The survivors of a plane crash are forced to live with each other on a mysterious island full of surprising secrets.", gradient: "linear-gradient(135deg,#0a1a0a,#1a3a1a,#0a1a2a)", accentColor: "#60a5fa", heroGradient: "linear-gradient(to right,#050a05,#0a1a0a,#050a05)", videoId: "jVkGfHLI1WY", category: "tvshows", tags: ["Mystery","Island","Ensemble"], language: "English" },
  { id: 204, title: "Cobra Kai", tmdbId: 77169, tmdbType: "tv", genre: "Martial Arts · Drama", rating: "TV-14", match: 91, year: 2024, duration: "6 Seasons", description: "Decades after their original battle, Johnny Lawrence seeks redemption by reopening the Cobra Kai karate dojo.", gradient: "linear-gradient(135deg,#1a0000,#3a0000,#3a1a00)", accentColor: "#f59e0b", heroGradient: "linear-gradient(to right,#0a0000,#1a0000,#0a0000)", videoId: "xCwwxNpUKOo", category: "tvshows", tags: ["Netflix","Karate Kid","Sequel"], language: "English" },

  // ── EXTRA WORLD CINEMA (to reach 20) ──
  { id: 211, title: "All Quiet on the Western Front", tmdbId: 765245, tmdbType: "movie", genre: "German · War", rating: "R", match: 96, year: 2022, duration: "2h 28m", description: "A German youth rushes to enlist in World War I, but the youthful excitement fades quickly into the brutal reality of war.", gradient: "linear-gradient(135deg,#1a1a00,#2d2d00,#3d3d10)", accentColor: "#d4a017", heroGradient: "linear-gradient(to right,#0a0a00,#1a1a00,#0a0a00)", videoId: "qp24lODU0V0", category: "world", tags: ["German","Oscar Winner","Anti-War"], language: "German" },
  { id: 212, title: "RRR", tmdbId: 759544, tmdbType: "movie", genre: "Indian · Action", rating: "NR", match: 97, year: 2022, duration: "3h 2m", description: "A fictional story about two revolutionaries' journey away from home before they take on the fight for their country.", gradient: "linear-gradient(135deg,#8a0000,#1a0a00,#0a0a3a)", accentColor: "#f97316", heroGradient: "linear-gradient(to right,#400000,#8a0000,#400000)", videoId: "f_vbAtFSEc0", category: "world", tags: ["Telugu","Action","Blockbuster"], language: "Telugu/Hindi" },
  { id: 213, title: "Money Heist: Korea", tmdbId: 130392, tmdbType: "tv", genre: "Korean · Heist", rating: "TV-MA", match: 91, year: 2022, duration: "2 Parts", description: "Genius strategist 'the Professor' recruits eight thieves to pull off an unprecedented heist on the Korean Mint.", gradient: "linear-gradient(135deg,#8a0000,#cc0000,#1a1a1a)", accentColor: "#ef4444", heroGradient: "linear-gradient(to right,#400000,#8a0000,#400000)", videoId: "JaIAl2Xo1v4", category: "world", tags: ["Korean","Heist","Netflix"], language: "Korean" },
  { id: 214, title: "Lupin", tmdbId: 96677, tmdbType: "tv", genre: "French · Thriller", rating: "TV-MA", match: 94, year: 2021, duration: "3 Parts", description: "Inspired by the adventures of Arsène Lupin, gentleman burglar, Assane Diop sets out to avenge his father's death.", gradient: "linear-gradient(135deg,#0a1a2a,#1a3a5a,#2a5a8a)", accentColor: "#60a5fa", heroGradient: "linear-gradient(to right,#050810,#0a1a2a,#050810)", videoId: "4KSgMdkAAzc", category: "world", tags: ["French","Netflix","Thriller"], language: "French" },
  { id: 215, title: "Sacred Games", tmdbId: 79340, tmdbType: "tv", genre: "Indian · Crime", rating: "TV-MA", match: 93, year: 2019, duration: "2 Seasons", description: "A police officer in Mumbai receives a mysterious tip from a gangster, leading to a major conspiracy.", gradient: "linear-gradient(135deg,#1a0a00,#3a1a00,#2a0a1a)", accentColor: "#f97316", heroGradient: "linear-gradient(to right,#0a0500,#1a0a00,#0a0500)", videoId: "NTfWlYSgFGA", category: "world", tags: ["India","Netflix","Crime"], language: "Hindi" },
  { id: 216, title: "Komi Can't Communicate", tmdbId: 100764, tmdbType: "tv", genre: "Japanese · Romance", rating: "TV-PG", match: 90, year: 2022, duration: "2 Seasons", description: "Komi has a communication disorder and aims to make 100 friends at her new school, starting with her first friend Tadano.", gradient: "linear-gradient(135deg,#0a0a2a,#1a1a4a,#2a2a6a)", accentColor: "#a78bfa", heroGradient: "linear-gradient(to right,#050510,#0a0a2a,#050510)", videoId: "APvUPxuuCxM", category: "world", tags: ["Anime","Romance","School"], language: "Japanese" },
  { id: 217, title: "Fauda", tmdbId: 66985, tmdbType: "tv", genre: "Israeli · Thriller", rating: "TV-MA", match: 95, year: 2022, duration: "4 Seasons", description: "An Israeli undercover unit chases a dangerous Hamas militant who has returned to carry out a new attack.", gradient: "linear-gradient(135deg,#1a1a00,#2a2a00,#3a2a00)", accentColor: "#fbbf24", heroGradient: "linear-gradient(to right,#0a0a00,#1a1a00,#0a0a00)", videoId: "Eym0wBxKQeY", category: "world", tags: ["Israeli","Netflix","Thriller"], language: "Hebrew" },
  { id: 218, title: "Vis a Vis (Locked Up)", tmdbId: 74802, tmdbType: "tv", genre: "Spanish · Drama", rating: "TV-MA", match: 91, year: 2019, duration: "4 Seasons", description: "A vulnerable young woman lands herself in a maximum-security prison after being manipulated by her boss.", gradient: "linear-gradient(135deg,#3a0060,#6a00aa,#1a1a1a)", accentColor: "#c084fc", heroGradient: "linear-gradient(to right,#1a0030,#3a0060,#1a0030)", videoId: "s0oDLPVIYeA", category: "world", tags: ["Spanish","Prison","Drama"], language: "Spanish" },
  { id: 219, title: "Elite", tmdbId: 79175, tmdbType: "tv", genre: "Spanish · Thriller", rating: "TV-MA", match: 89, year: 2023, duration: "7 Seasons", description: "Three working class kids are expelled from their school and enrolled in an elite academy — clashes lead to a murder.", gradient: "linear-gradient(135deg,#1a0a2a,#2a1a4a,#3a2a6a)", accentColor: "#c084fc", heroGradient: "linear-gradient(to right,#0a0515,#1a0a2a,#0a0515)", videoId: "cFPPYGiYEqQ", category: "world", tags: ["Spanish","Netflix","Teen Thriller"], language: "Spanish" },
  { id: 220, title: "The Kingdom", tmdbId: 37185, tmdbType: "tv", genre: "Danish · Horror", rating: "TV-MA", match: 90, year: 2022, duration: "3 Seasons", description: "Strange events unfold at a hospital built on an ancient bog where the boundaries between the living and dead are blurred.", gradient: "linear-gradient(135deg,#0a0a1a,#1a1a2a,#0a1a0a)", accentColor: "#86efac", heroGradient: "linear-gradient(to right,#050508,#0a0a1a,#050508)", videoId: "BFg5E6Z2_zY", category: "world", tags: ["Danish","Horror","Lars von Trier"], language: "Danish" },
  { id: 221, title: "Call My Agent!", tmdbId: 66855, tmdbType: "tv", genre: "French · Comedy", rating: "TV-14", match: 92, year: 2020, duration: "4 Seasons", description: "The staff of a Parisian talent agency navigate the demands of their diva clients while dealing with personal crises.", gradient: "linear-gradient(135deg,#1a1a1a,#2a2a2a,#1a0a1a)", accentColor: "#f0abfc", heroGradient: "linear-gradient(to right,#0a0a0a,#1a1a1a,#0a0a0a)", videoId: "hC7YOHAnGb8", category: "world", tags: ["French","Comedy","Netflix"], language: "French" },
  { id: 222, title: "Alice in Borderland", tmdbId: 101299, tmdbType: "tv", genre: "Japanese · Sci-Fi", rating: "TV-MA", match: 94, year: 2022, duration: "2 Seasons", description: "A young man and his friends find themselves in a post-apocalyptic world where they must compete in games to survive.", gradient: "linear-gradient(135deg,#0a0a1a,#1a1a3a,#2a2a5a)", accentColor: "#818cf8", heroGradient: "linear-gradient(to right,#050508,#0a0a1a,#050508)", videoId: "6MHTcHMIHek", category: "world", tags: ["Japanese","Netflix","Survival"], language: "Japanese" },
  { id: 223, title: "Crash Landing on You", tmdbId: 92498, tmdbType: "tv", genre: "Korean · Romance", rating: "TV-14", match: 95, year: 2020, duration: "1 Season", description: "A South Korean heiress accidentally crash-lands in North Korea and falls in love with a military officer.", gradient: "linear-gradient(135deg,#0a2a1a,#1a5a3a,#0a0a2a)", accentColor: "#86efac", heroGradient: "linear-gradient(to right,#050f0a,#0a2a1a,#050f0a)", videoId: "rEWPbYjjUng", category: "world", tags: ["K-Drama","Romance","Netflix"], language: "Korean" },
  { id: 224, title: "Dark Waters (Dark)", tmdbId: 70523, tmdbType: "tv", genre: "German · Mystery", rating: "TV-MA", match: 97, year: 2020, duration: "3 Seasons", description: "A family saga with a supernatural twist, set in a German town, where the disappearance of two young children exposes the double lives of its residents.", gradient: "linear-gradient(135deg,#0f0c29,#302b63,#24243e)", accentColor: "#9b59b6", heroGradient: "linear-gradient(to right,#000000,#1a1a2e,#000000)", videoId: "rrwycJ08PSA", category: "world", tags: ["German","Time Travel","Mystery"], language: "German" },
  { id: 225, title: "The 100", tmdbId: 48866, tmdbType: "tv", genre: "Sci-Fi · Post-Apocalyptic", rating: "TV-14", match: 88, year: 2020, duration: "7 Seasons", description: "A century after nuclear war, 100 juvenile delinquents are sent to Earth to see if the planet is survivable.", gradient: "linear-gradient(135deg,#0a2a0a,#1a5a1a,#0a0a1a)", accentColor: "#4ade80", heroGradient: "linear-gradient(to right,#050f05,#0a2a0a,#050f05)", videoId: "ia5rgBzOSoA", category: "world", tags: ["CW","Post-Apocalyptic","Sci-Fi"], language: "English" },
];

export const DEFAULT_HERO = MOVIES[0];

export const HERO_SLIDES = [
  MOVIES[3],  // Arcane
  MOVIES[0],  // Stranger Things
  MOVIES[1],  // Squid Game
  MOVIES[2],  // Wednesday
  MOVIES[4],  // Dark
  MOVIES[10], // Oppenheimer (index 10 = hits[0])
  MOVIES[11], // Dune Part Two
];

export const CATEGORIES = {
  trending:  { label: "🔥 Trending Now" },
  hits:      { label: "🏆 Blockbuster Hits" },
  new:       { label: "✨ New on Netflix" },
  cartoon:   { label: "🎨 Cartoons & Animation" },
  adventure: { label: "⚔️ Epic Adventures" },
  tvshows:   { label: "📺 Popular TV Shows" },
  family:    { label: "🎉 Action & Family" },
  world:     { label: "🌏 World Cinema" },
};
